# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de85e59f5b9c789804a092ddcc5e7aa79a2f575f314bc49f1a2ad1201a85c72bde00c7fab6af2ad36000989497458fb8f8f0e78903aa87c1095fc50e3f5729b1

test:
  secret_key_base: 99435c6db2f7d4cb7ef81abe92da2a5ada7fc3ac015acf13d4cf2c180b44fc38f4892d74fc5f28438ba0c91da162426980865d879014794e28439adf26f7e348

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
